---
- name: DNF check for updates
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check packages to upgrade
      ansible.builtin.dnf:
        list: updates
      register: packages

    - name: Show packages to upgrade
      ansible.builtin.debug:
        msg: "{{ packages }}"

    - name: Show packages to upgrade
      ansible.builtin.debug:
        msg: >-
          {%- set output=[] -%}
          {%- for p in packages.results -%}
          {{ output.append('%-40s' % (p.name ~ '-' ~ p.version) ~ ' | repo: ' ~ p.repo) }}
          {%- endfor -%}
          {{ output }}
