---
- name: Install Full System
  hosts: localhost
  vars:
    kvm: false
    vpn: false
    sway: false
    xfce: false

  roles:
    - role: browsers
    - role: bruno
    - role: common-terminal
    - role: common-desktop
    - role: development-tools
    - role: vscode
    - role: zed-editor
    - role: openfortivpn
    - role: tailscale
      when: vpn | bool
    - role: slack
    - role: virtualization
      when: kvm | bool
    - role: sway
      when: sway | bool
    - role: xfce
      when: xfce | bool
    - role: docker
      when: "docker|default(false)|bool"
