---
- name: Install Full System
  hosts: localhost

  roles:
    - role: browsers
    - role: bruno
    - role: common-terminal
    - role: common-desktop
    - role: development-tools
    - role: vscode
    - role: zed-editor
    - role: openfortivpn
    - role: tailscale
      when: VPN | bool
    - role: slack
    - role: virtualization
      when: KVM | bool
    - role: sway
      when: SWAY | bool
    - role: xfce
      when: XFCE | bool
