---
- name: Install Full System
  hosts: localhost

  roles:
    - role: browsers
    - role: bruno
    - role: common-terminal
    - role: common-desktop
    - role: development-tools
    - role: vscode
    - role: zed-editor
    - role: openfortivpn
      when: "vpn|default(false)|bool"
    - role: tailscale
      when: "vpn|default(false)|bool"
    - role: slack
      when: "slack|default(false)|bool"
    - role: virtualization
      when: "kvm|default(false)|bool"
    - role: sway
      when: "sway|default(false)|bool"
    - role: xfce
      when: "xfce|default(false)|bool"
    - role: docker
      when: "docker|default(false)|bool"
