---
- name: Install XFCE packages
  community.general.pacman:
    name:
      - alsa-lib
      - alsa-utils
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - sddm
      - xfce4
      - xfce4-goodies
      - xfce4-whiskermenu-plugin
      - xorg
      - xorg-server
    extra_args: --needed
    state: present

- name: Install Sway AUR packages
  kewlfft.aur.aur:
    name:
      - catppuccin-sddm-theme-mocha
    extra_args: --needed
    use: yay
    state: present
  become: yes
  become_user: aur_builder
