---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install common packages
  community.general.pacman:
    name: "{{ common_desktop }}"
    extra_args: --needed
    state: present

- name: Install common AUR packages
  kewlfft.aur.aur:
    name: "{{ common_desktop_aur }}"
    use: yay
    state: present
    extra_args: --needed
  become: yes
  become_user: aur_builder
