---
- name: Install Tailscale
  community.general.pacman:
    name:
      - tailscale
    extra_args: --needed
    state: present

- name: Enable Tailscale service
  ansible.builtin.systemd_service:
    name: tailscaled.service
    enabled: true
    state: started
