---
- name: Install Browsers
  kewlfft.aur.aur:
    name:
      - brave-bin
      - microsoft-edge-stable-bin
      - google-chrome
    use: yay
    state: present
  become: yes
  become_user: aur_builder
