---
- name: Get the non root remote user
  ansible.builtin.set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Add Docker repo
  ansible.builtin.yum_repository:
    name: docker
    description: Docker repo
    baseurl: "https://download.docker.com/linux/fedora/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
    gpgkey: "https://download.docker.com/linux/fedora/gpg"
    gpgcheck: true
    enabled: true

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ remote_regular_user }}"
    groups: docker
    append: true
