---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install Sway pacman packages
  community.general.pacman:
    name: "{{ sway_pacman_packages }}"
    state: present

- name: Install Sway AUR packages
  kewlfft.aur.aur:
    name: "{{ sway_aur_packages }}"
    use: yay
    state: present
  become: yes
  become_user: aur_builder
