---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install Sway Desktop
  community.general.pacman:
    executable: yay
    extra_args: --builddir /tmp/yay
    name: "{{ sway_packages }}"
    state: present
