---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install Sway Desktop
  community.general.pacman:
    become: false
    executable: yay
    name: "{{ sway_packages }}"
    state: present
