---
- name: Check for distribution specific configs
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distro_config

- name: Run tasks for distribution specific configs
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  when: distro_config.stat.exists
