---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install Common Terminal packages
  community.general.pacman:
    name: "{{ common_terminal }}"
    extra_args: --needed
    state: present

- name: Enable ssh service
  become: true
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: true
